name = "ParameterSchedulers"
uuid = "d7d3b36b-41b8-4d0d-a2bf-768c6151755e"
authors = ["Kyle Daruwalla"]
version = "0.3.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
InfiniteArrays = "4858937d-0d70-526a-a4dd-2d5cb5dd786c"

[compat]
Flux = "0.11.2, 0.12"
InfiniteArrays = "0.10.4, 0.11, 0.12"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[publish]
ignore = ["^(gh-pages|juliamnt|julia.dmg)$"]
theme = "_flux-theme"
title = "ParameterSchedulers.jl"

[targets]
test = ["Test"]
